# Tweets with Geo Location

To get user profile location -> have to search by city (most exact if search is by long/lat)

In [1]:
#Importing other libraries
import pandas as pd
import numpy as np
import snscrape.modules.twitter as sntwitter
import itertools
import time

In [2]:
#20 largest US cities
city_lst = ['Los Angeles', 'New York', 'Chicago', 'Houston', 'Philadelphia', 'Phoenix', 'San Antonio', 'San Diego', 'Dallas', 
           'San Jose', 'Honolulu', 'Austin', 'Indianapolis', 'Jacksonville', 'San Francisco', 'Columbus', 'Charlotte', 'Fort Worth', 
            'Detroit', 'El Paso']

coord_lst = ['34.052235, -118.243683, 15km', '40.6643, -73.9385, 15km', '41.8379,  -87.6828, 15km', '29.749907, -95.358421, 15km', 
      '39.952583, -75.165222, 15km', '33.448376, -112.074036, 15km', '29.424349, -98.491142, 15km', 
       '32.715736, -117.161087,15km', '32.779167, -96.808891, 15km', '37.335480, -121.893028, 15km', '21.315603, -157.858093, 15km',
      '30.266666, -97.733330, 15km', '39.791000, -86.148003, 15km', '30.332184, -81.655647, 15km', '37.773972, -122.431297, 15km',
      '39.983334, -82.983330, 15km', '35.227085, -80.843124, 15km', '32.768799, -97.309341, 15km', '42.331429, -83.045753, 15km',
      '31.772543, -106.460953, 15km']

In [3]:
#starting dataframe

loc = '34.052235, -118.243683, 10km'
df = pd.DataFrame(itertools.islice(sntwitter.TwitterSearchScraper(
    '(climate change) OR (global warming) exclude:replies exclude:retweets lang:en geocode:"{}"'.format(loc)).get_items(), 1))[['id', 'user', 'date','content']]

df['user_location'] =  df['user'].apply(lambda x: x['location'])
df['user_city'] = 'Los Angeles'

In [4]:
df

,id,user,date,content,user_location,user_city
0,1394303734839078913,"{'username': 'SjonesiProduce', 'displayname': ...",2021-05-17 14:48:09+00:00,@DallasTexasTV Y’all believe in climate change...,"Los Angeles, CA",Los Angeles

In [ ]:
'''
Version I: Looping in smaller quantities

#loop to scrap data with breaks and looping through different cities
count = 0

for city in coord_lst:
    mx = '1394289852967886852' #defining starting tweet
    for i in range(1, 2):
        count += 1
        if count < 20:
            print('Starting iterations')
            df1 = pd.DataFrame(itertools.islice(sntwitter.TwitterSearchScraper(
            '(climate change) exclude:replies exclude:retweets lang:en geocode:"{}" max_id:"{}"'.format(city, mx)).get_items(), 50))[['id', 'user', 'date','content']]
            df1['user_location'] =  df1['user'].apply(lambda x: x['location'])
            df1 = df1.iloc[1:]
            df = df.append(df1, ignore_index=True)
            mx = df1['id'].iloc[-1]
            print('Iteration #', i, 'done. City:', city)
            time.sleep(1)
        else:
            print('going to sleep')
            time.sleep(300)
            count = 0
            print('waking up')        
'''

In [5]:
#getting 500 tweets for every city:
for city, city_name in zip(coord_lst, city_lst):
    print('Starting iteration for:', city_name)
    mx = '1394303734839078913' #id from df
    df1 = pd.DataFrame(itertools.islice(sntwitter.TwitterSearchScraper(
            '(climate change) OR (global warming) exclude:replies exclude:retweets lang:en geocode:"{}" max_id:"{}"'.format(city, mx)).get_items(), 500))[['id', 'user', 'date','content']]
    df1['user_location'] =  df1['user'].apply(lambda x: x['location'])
    df1['user_city'] = city_name
    df1 = df1.iloc[1:]
    df = df.append(df1, ignore_index=True)
    #mx = df1['id'].iloc[-1]
    print('Done city:', city_name)
    time.sleep(180)

Starting iteration for: Los Angeles
Done city: Los Angeles
Starting iteration for: New York
Done city: New York
Starting iteration for: Chicago
Done city: Chicago
Starting iteration for: Houston
Done city: Houston
Starting iteration for: Philadelphia
Done city: Philadelphia
Starting iteration for: Phoenix
Done city: Phoenix
Starting iteration for: San Antonio
Done city: San Antonio
Starting iteration for: San Diego
Done city: San Diego
Starting iteration for: Dallas
Done city: Dallas
Starting iteration for: San Jose
Done city: San Jose
Starting iteration for: Honolulu
Done city: Honolulu
Starting iteration for: Austin
Done city: Austin
Starting iteration for: Indianapolis
Done city: Indianapolis
Starting iteration for: Jacksonville
Done city: Jacksonville
Starting iteration for: San Francisco
Done city: San Francisco
Starting iteration for: Columbus
Done city: Columbus
Starting iteration for: Charlotte
Done city: Charlotte
Starting iteration for: Fort Worth
Done city: Fort Worth
Starting iteration for: Detroit
Done city: Detroit
Starting iteration for: El Paso
Done city: El Paso

In [7]:
df

,id,user,date,content,user_location,user_city
0,1394296050903441413,"{'username': 'UrbanKaoboy', 'displayname': 'Mi...",2021-05-17 14:17:37+00:00,Musing of the Day: Cognitive dissonance — when...,"Los Angeles, CA",NaN
1,1394289852967886852,"{'username': 'TylerPrize', 'displayname': 'Tyl...",2021-05-17 13:53:00+00:00,To understand how we can properly #value #natu...,"Los Angeles, CA",Los Angeles
2,1394277302528184322,"{'username': 'urionsantos', 'displayname': 'Ur...",2021-05-17 13:03:07+00:00,Now that the Covid plandemic is over\n\nIt’s t...,"Los Angeles, CA",Los Angeles
3,1394223905339027459,"{'username': 'ChukarBlog', 'displayname': 'Chu...",2021-05-17 09:30:57+00:00,"The moon, the moon's nodes and climate change ...",Los Angeles,Los Angeles
4,1394187383952666628,"{'username': 'KiraDurbin', 'displayname': 'Kir...",2021-05-17 07:05:49+00:00,Our oceans are bearing the brunt of global war...,"Los Angeles, CA",Los Angeles
...,...,...,...,...,...,...
886,1392878685779283975,"{'username': 'JFrusci', 'displayname': 'Dr. Jo...",2021-05-13 16:25:31+00:00,"WATCH: @mikeallen, @margarettalev and @axiosni...","New York, NY",New York
887,1392878560885583873,"{'username': 'EpochTimes', 'displayname': 'The...",2021-05-13 16:25:02+00:00,Supporters of President Biden overestimate the...,"New York, USA",New York
888,1392876955196923904,"{'username': 'briebriejoy', 'displayname': 'Br...",2021-05-13 16:18:39+00:00,‼️New @BadFaithPod: Why We Can't Capitalism ou...,"Manhattan, NY",New York
889,1392875993447215107,"{'username': 'OneSignalPub', 'displayname': 'O...",2021-05-13 16:14:49+00:00,“Having relevant indicators...helps us connect...,"New York, NY",New York
890,1392875551464075271,"{'username': 'itsalexberg', 'displayname': 'Al...",2021-05-13 16:13:04+00:00,"On the @lgbtqnation podcast, we're talking abo...",New York City,New York

In [12]:
df.iloc[350:400]

,id,user,date,content,user_location,user_city
350,1175115515636768768,"{'username': 'greenwtiffany', 'displayname': '...",2019-09-20 18:32:26+00:00,The Time Is Now!!\n#globalclimatestrike #choos...,"Los Angeles, CA",Los Angeles
351,1171652879184289798,"{'username': 'MichaelKaliski', 'displayname': ...",2019-09-11 05:13:09+00:00,Important and inspiring film. See it and be pa...,"Los Angeles, CA",Los Angeles
352,1169808403352489984,"{'username': '_arielmichele', 'displayname': '...",2019-09-06 03:03:52+00:00,"autumn will begin shortly enough, and while i ...",under the sea,Los Angeles
353,1169696638517932032,"{'username': 'Fiorella_im', 'displayname': 'Fi...",2019-09-05 19:39:45+00:00,Bernie’s climate action plan was by far the be...,"Los Angeles, CA",Los Angeles
354,1169287248740847616,"{'username': 'bentpieceofwire', 'displayname':...",2019-09-04 16:32:59+00:00,soon it’ll be crispy fall and we can practice ...,"Los Angeles, CA",Los Angeles
355,1169018448795623426,"{'username': 'djpaulomusic', 'displayname': 'D...",2019-09-03 22:44:52+00:00,So sad the images coming out of the Bahamas. I...,Los Angeles,Los Angeles
356,1168683706745311237,"{'username': 'sydneyvieng', 'displayname': 'Sy...",2019-09-03 00:34:43+00:00,Auditioning for the first Southeast Asian supe...,"Los Angeles, CA",Los Angeles
357,1168675000439562240,"{'username': 'JustADayinLA', 'displayname': 'J...",2019-09-03 00:00:07+00:00,Happy #LaborDay ! Hope you aren’t polluting! I...,Los Angeles,Los Angeles
358,1167264578876538880,"{'username': 'alyssaalarraa', 'displayname': '...",2019-08-30 02:35:36+00:00,bro climate change is a real thing... don’t di...,,Los Angeles
359,1166359935749435394,"{'username': 'RevJuju', 'displayname': 'RevJuj...",2019-08-27 14:40:53+00:00,"Timely discussion on Climate change, all are i...",Cali.,Los Angeles
360,1166202015770234880,"{'username': 'RevJuju', 'displayname': 'RevJuj...",2019-08-27 04:13:22+00:00,WOE Family we need you in the house tomorrow n...,Cali.,Los Angeles
361,1164944000811274240,"{'username': 'djpaulomusic', 'displayname': 'D...",2019-08-23 16:54:28+00:00,With everything that’s going on global warming...,Los Angeles,Los Angeles
362,1164663695965745152,"{'username': 'london367de', 'displayname': 'Do...",2019-08-22 22:20:38+00:00,Scary images - trees are an important solution...,,Los Angeles
363,1164650632264867840,"{'username': 'london367de', 'displayname': 'Do...",2019-08-22 21:28:43+00:00,Scary images. Our best tool to combat climate...,,Los Angeles
364,1164473978573877249,"{'username': 'ronnymorris', 'displayname': 'RO...",2019-08-22 09:46:46+00:00,The lyric video for “Built to Last” is now ava...,"Los Angeles, Califormia",Los Angeles
365,1164328390570024961,"{'username': 'drcatmeyer', 'displayname': 'Dr....",2019-08-22 00:08:15+00:00,LOVE. With so many events and change to our so...,"Los Angeles, CA",Los Angeles
366,1162180289881186305,"{'username': 'ZackWickham', 'displayname': 'Za...",2019-08-16 01:52:28+00:00,You know how some people are climate change de...,"Los Angeles, CA",Los Angeles
367,1161648516537565186,"{'username': 'ronnymorris', 'displayname': 'RO...",2019-08-14 14:39:23+00:00,The single titled “Built to Last” is Available...,"Los Angeles, Califormia",Los Angeles
368,1159650135590096896,"{'username': 'gudiel', 'displayname': 'Gudiel ...",2019-08-09 02:18:32+00:00,Totally respect this. We need more bikes and l...,"Los Angeles, CA",Los Angeles
369,1159444387371159557,"{'username': 'athornythicket', 'displayname': ...",2019-08-08 12:40:58+00:00,Climate Change Threatens the World’s Food Supp...,"South Pasadena, Ca",Los Angeles
370,1157168855082397697,"{'username': 'athornythicket', 'displayname': ...",2019-08-02 05:58:48+00:00,"We can’t avoid it any longer, climate change a...","South Pasadena, Ca",Los Angeles
371,1155260919305236480,"{'username': 'hotegallery', 'displayname': 'Ho...",2019-07-27 23:37:21+00:00,Enough to go around by Cory Sewelson #okeanos ...,"Alhambra, CA",Los Angeles
372,1155225379914674177,"{'username': 'hotegallery', 'displayname': 'Ho...",2019-07-27 21:16:08+00:00,Pink Sky by Luciana Abait #okeanos #laartist #...,"Alhambra, CA",Los Angeles
373,1155202626310434816,"{'username': 'hotegallery', 'displayname': 'Ho...",2019-07-27 19:45:43+00:00,Climate change: 12 years to save the planet? M...,"Alhambra, CA",Los Angeles
374,1154836486698569728,"{'username': 'hotegallery', 'displayname': 'Ho...",2019-07-26 19:30:48+00:00,"Last days to view ""Ōkeanós"" 🌊the exhibit addre...","Alhambra, CA",Los Angeles
375,1154712733943656448,"{'username': 'ScottStenholm', 'displayname': '...",2019-07-26 11:19:03+00:00,The fact that a large segment of our society i...,"Los Angeles, California",Los Angeles
376,1154485055730810880,"{'username': 'CleanairCA', 'displayname': 'Coa...",2019-07-25 20:14:21+00:00,Special shout out for our intern Helen on #Nat...,California,Los Angeles
377,1153073837317246978,"{'username': 'simcarter', 'displayname': '📚Sim...",2019-07-21 22:46:40+00:00,Summertime and the living is ...\nLA is a balm...,"Los Angeles, CA",Los Angeles
378,1150543999700094977,"{'username': 'nadrawidatalla', 'displayname': ...",2019-07-14 23:14:00+00:00,We brought over 300 ppl together to engage in ...,,Los Angeles
379,1148699757772247040,"{'username': 'gogreenwealth', 'displayname': '...",2019-07-09 21:05:38+00:00,Energy Efficiency is simple and easy with the ...,"Pasadena, CA",Los Angeles
380,1148430664427016192,"{'username': 'kevinscasasola', 'displayname': ...",2019-07-09 03:16:21+00:00,"Fight for justice, fight for peace, fight for ...","Murrieta, CA",Los Angeles
381,1147551941079289858,"{'username': 'AngelCityTV', 'displayname': 'An...",2019-07-06 17:04:37+00:00,"And, just like in my dreams, cue the meteors. ...","Los Angeles, California",Los Angeles
382,1147394082546700288,"{'username': 'MathieuOwens', 'displayname': 'M...",2019-07-06 06:37:21+00:00,JUST SAYING #climatechange https://t.co/RhSk3Z...,"South Pasadena, CA",Los Angeles
383,1146465551855824896,"{'username': 'AnthonyMeindl', 'displayname': '...",2019-07-03 17:07:42+00:00,Congrats to the wonderful babshowlin &amp; the...,LA/NY/ATL/Toronto/London/Vancouver/Sydney/SantaFe,Los Angeles
384,1145909458448474113,"{'username': 'lac4justice', 'displayname': 'Lu...",2019-07-02 04:17:59+00:00,Rachel Maddow:USDA Scientists produced penicil...,,Los Angeles
385,1145843334532829184,"{'username': 'alerod123', 'displayname': 'Alej...",2019-07-01 23:55:14+00:00,Yea climate change isn’t real 😐 https://t.co/7...,"North Hollywood, Los Angeles",Los Angeles
386,1144341766704734208,"{'username': 'dontrockwobble', 'displayname': ...",2019-06-27 20:28:32+00:00,"""climate change is real"" - bernie sanders + th...",midnight city 🌃🌴🌅,Los Angeles
387,1144069750013616129,"{'username': 'jacobs_farms', 'displayname': 'J...",2019-06-27 02:27:38+00:00,To get canadain vote all you have to do is pro...,Daysland Alberta,Los Angeles
388,1136872785723109377,"{'username': 'lac4justice', 'displayname': 'Lu...",2019-06-07 05:49:28+00:00,MORON-IN-CHIEF TRUMP knows Nothing about clima...,,Los Angeles
389,1136872004831735809,"{'username': 'lac4justice', 'displayname': 'Lu...",2019-06-07 05:46:22+00:00,NY Times' Kristof interviewed people in Guatem...,,Los Angeles
390,1136553391071596544,"{'username': 'wendygkennedy', 'displayname': '...",2019-06-06 08:40:19+00:00,"The day y'all ever see me talking about ""Clima...",Littlerock.CA,Los Angeles
391,1134471776493195264,"{'username': 'jonnyjournal', 'displayname': 'j...",2019-05-31 14:48:43+00:00,😫Climate change link to puffin deaths #BBCNews...,"Los Angeles, CA",Los Angeles
392,1394294852955869185,"{'username': 'kdgscribe', 'displayname': 'Keit...",2021-05-17 14:12:52+00:00,BREAKING: #SCOTUS vacates 4th Circuit ruling r...,New York,New York
393,1394294544531918851,"{'username': 'm4ndym', 'displayname': 'Amanda ...",2021-05-17 14:11:38+00:00,"The double ones were gifts, so was Arkham Asyl...","New York, USA",New York
394,1394294214658297856,"{'username': 'ecoathletesteam', 'displayname':...",2021-05-17 14:10:20+00:00,Amazing work by our friend @maddyjorr! Check o...,"New York, NY",New York
395,1394294143518658564,"{'username': 'NYGreenBuilding', 'displayname':...",2021-05-17 14:10:03+00:00,Radio BE-Ex: Building #Retrofits as Climate Ac...,New York,New York
396,1394292871306563588,"{'username': 'NexusMediaNews', 'displayname': ...",2021-05-17 14:04:59+00:00,Biden could give a much-needed boost to countr...,"New York, NY",New York
397,1394292023499366416,"{'username': 'scifri_ebooks', 'displayname': '...",2021-05-17 14:01:37+00:00,Scientists have mapped microbes around the wor...,"Manhattan, NY",New York
398,1394291899415113733,"{'username': 'RolandLaVoix', 'displayname': 'R...",2021-05-17 14:01:08+00:00,.@POTUS @JohnKerry the world needs America’s h...,New York,New York
399,1394291869291515908,"{'username': 'UrbanFutureLab', 'displayname': ...",2021-05-17 14:01:00+00:00,The deadline for the Urban Future Prize Compet...,"New York, NY",New York

In [6]:
df

,id,user,date,content,user_location,user_city
0,1394303734839078913,"{'username': 'SjonesiProduce', 'displayname': ...",2021-05-17 14:48:09+00:00,@DallasTexasTV Y’all believe in climate change...,"Los Angeles, CA",Los Angeles
1,1394296050903441413,"{'username': 'UrbanKaoboy', 'displayname': 'Mi...",2021-05-17 14:17:37+00:00,Musing of the Day: Cognitive dissonance — when...,"Los Angeles, CA",Los Angeles
2,1394289852967886852,"{'username': 'TylerPrize', 'displayname': 'Tyl...",2021-05-17 13:53:00+00:00,To understand how we can properly #value #natu...,"Los Angeles, CA",Los Angeles
3,1394285402672955396,"{'username': 'navajeremy14', 'displayname': 'J...",2021-05-17 13:35:19+00:00,Time for people to blame everything but global...,"Rosemead, CA",Los Angeles
4,1394277302528184322,"{'username': 'urionsantos', 'displayname': 'Ur...",2021-05-17 13:03:07+00:00,Now that the Covid plandemic is over\n\nIt’s t...,"Los Angeles, CA",Los Angeles
...,...,...,...,...,...,...
8307,234659452563894273,"{'username': 'Bravocanyonal', 'displayname': '...",2012-08-12 14:35:47+00:00,You want to stop 1. Global warming 2. Rising s...,"El Paso, Texas",El Paso
8308,181899407267074048,"{'username': 'whateverboi88', 'displayname': '...",2012-03-20 00:26:12+00:00,Man..this morning it was windy...rained...hail...,el paso,El Paso
8309,148662327183552512,"{'username': 'amarie_g_', 'displayname': 'Anto...",2011-12-19 07:13:55+00:00,A thunderstorm in the middle of the winter??? ...,"Right On The Edge Of, TX",El Paso
8310,104344407859404800,"{'username': 'thedesertape', 'displayname': 'I...",2011-08-19 00:10:20+00:00,RickPerry said GlobalWarming isNOT caused by m...,"TeXas, west of Hueco Tanks",El Paso
8311,101403182424530944,"{'username': 'Cmpepsi', 'displayname': 'Cruz N...",2011-08-10 21:22:57+00:00,Global warming is cause of @xOBx_DjEddie ... A...,"El Paso, TX",El Paso

In [7]:
df['user_city'].value_counts()

Los Angeles      500
San Jose         499
Chicago          499
Philadelphia     499
Detroit          499
Houston          499
San Francisco    499
Phoenix          499
San Diego        499
Dallas           499
New York         499
Austin           499
Columbus         483
Honolulu         416
San Antonio      391
Charlotte        380
Indianapolis     259
Fort Worth       214
El Paso          110
Jacksonville      70
Name: user_city, dtype: int64

In [10]:
df.sort_values('date', ascending=False)

,id,user,date,content,user_location,user_city
0,1394303734839078913,"{'username': 'SjonesiProduce', 'displayname': ...",2021-05-17 14:48:09+00:00,@DallasTexasTV Y’all believe in climate change...,"Los Angeles, CA",Los Angeles
500,1394301437354684417,"{'username': 'PaigeWestNYC', 'displayname': 'P...",2021-05-17 14:39:02+00:00,GREAT piece about the Oreskes / Supran work on...,New York City,New York
501,1394300765406175238,"{'username': 'Inn_Fin_Grp', 'displayname': 'In...",2021-05-17 14:36:21+00:00,"Pandemics, Climate Change, Recessions – Oh my!...","New York, USA",New York
502,1394299475368218630,"{'username': 'CityLab', 'displayname': 'Bloomb...",2021-05-17 14:31:14+00:00,To address challenges like climate change and ...,"New York, NY",New York
503,1394298302707929089,"{'username': 'Law360', 'displayname': 'Law360'...",2021-05-17 14:26:34+00:00,BREAKING: The Supreme Court nixed the Fourth C...,New York,New York
...,...,...,...,...,...,...
7107,49637069609369601,"{'username': 'Craze_TOS', 'displayname': 'Kami...",2011-03-21 01:02:54+00:00,Am I the only one scared of #GlobalWarming?,"Marietta, GA",Columbus
5296,32620965917626368,"{'username': 'BluePlanetFound', 'displayname':...",2011-02-02 02:06:59+00:00,http://tinyurl.com/SB722: Amended HI barrel ta...,"Honolulu, Hawaii",Honolulu
7108,11541725591896064,"{'username': 'mlopreste', 'displayname': 'Mike...",2010-12-05 22:05:36+00:00,writing about climate change. everytime i read...,,Columbus
5297,2963355933343745,"{'username': '96822', 'displayname': '96822', ...",2010-11-12 05:58:13+00:00,New Study: Global Warming Changes Hurricanes h...,96822,Honolulu
5298,27913797907,"{'username': '96814', 'displayname': '96814', ...",2010-10-20 08:56:37+00:00,"Climate change could change El Nino, campaigns...",96814,Honolulu