# Tweets without Geo Location

Scrapping data using the following key words:

- climate change
- global warming

Filters:

- excluding retweets and replies
- only including english tweets

Using snscraper: https://github.com/MartinBeckUT/TwitterScraper/tree/master/snscrape/python-wrapper

Search options: https://github.com/igorbrigadir/twitter-advanced-search

In [34]:
#Importing other libraries
import pandas as pd
import numpy as np
import snscrape.modules.twitter as sntwitter
import itertools
import time

In [4]:
df = pd.DataFrame(itertools.islice(sntwitter.TwitterSearchScraper(
    '(climate change) OR (global warming) OR (climate hoax) exclude:replies exclude:retweets lang:en').get_items(), 10))[['id', 'date', 'content', 'coordinates', 'place', 'user']]

In [24]:
count = 0

for i in range(1, 20000):
    count += 1
    if count < 100:
        print('Starting iterations')
        mx = df['id'].iloc[-1]
        df1 = pd.DataFrame(itertools.islice(sntwitter.TwitterSearchScraper(
            '(climate change) OR (global warming) OR (climate hoax) OR (climate deniers) exclude:replies exclude:retweets lang:en max_id:%s' % mx).get_items(), 50))[['id', 'date', 'content', 'coordinates', 'place', 'user']]
        df1 = df1.iloc[1:]
        df = df.append(df1, ignore_index=True)
        print('Iteration #', i, 'done.')
        time.sleep(1)
    else:
        print('going to sleep')
        time.sleep(600)
        count = 0
        print('waking up')
        continue

Starting iterations
Iteration # 1 done.
Starting iterations
Iteration # 2 done.
Starting iterations
Iteration # 3 done.
Starting iterations
Iteration # 4 done.
Starting iterations
Iteration # 5 done.
Starting iterations
Iteration # 6 done.
Starting iterations
Iteration # 7 done.
Starting iterations
Iteration # 8 done.
Starting iterations
Iteration # 9 done.
Starting iterations
Iteration # 10 done.
Starting iterations
Iteration # 11 done.
Starting iterations
Iteration # 12 done.
Starting iterations
Iteration # 13 done.
Starting iterations
Iteration # 14 done.
Starting iterations
Iteration # 15 done.
Starting iterations
Iteration # 16 done.
Starting iterations
Iteration # 17 done.
Starting iterations
Iteration # 18 done.
Starting iterations
Iteration # 19 done.
Starting iterations
Iteration # 20 done.
Starting iterations
Iteration # 21 done.
Starting iterations
Iteration # 22 done.
Starting iterations
Iteration # 23 done.
Starting iterations
Iteration # 24 done.
Starting iterations
Iteration # 25 done.
Starting iterations
Iteration # 26 done.
Starting iterations
Iteration # 27 done.
Starting iterations
Iteration # 28 done.
Starting iterations
Iteration # 29 done.
Starting iterations
Iteration # 30 done.
Starting iterations
Iteration # 31 done.
Starting iterations
Iteration # 32 done.
Starting iterations
Iteration # 33 done.
Starting iterations
Iteration # 34 done.
Starting iterations
Iteration # 35 done.
Starting iterations
Iteration # 36 done.
Starting iterations
Iteration # 37 done.
Starting iterations
Iteration # 38 done.
Starting iterations
Iteration # 39 done.
Starting iterations
Iteration # 40 done.
Starting iterations
Iteration # 41 done.
Starting iterations
Iteration # 42 done.
Starting iterations
Iteration # 43 done.
Starting iterations
Iteration # 44 done.
Starting iterations
Iteration # 45 done.
Starting iterations
Iteration # 46 done.
Starting iterations
Iteration # 47 done.
Starting iterations
Iteration # 48 done.
Starting iterations
Iteration # 49 done.
going to sleep

KeyboardInterrupt:

In [28]:
df.tail(3)

,id,date,content,coordinates,place,user
7187,1393662975039442948,2021-05-15 20:22:00+00:00,Opinion: It’s time to recommit to controlling ...,None,None,"{'username': 'ColoradoSun', 'displayname': 'Th..."
7188,1393662967024082945,2021-05-15 20:21:59+00:00,WARNINGS OF THE DESTRUCTION CLIMATE CHANGE IS ...,None,None,"{'username': 'Sonialowe1938', 'displayname': '..."
7189,1393662860031520768,2021-05-15 20:21:33+00:00,If climate change is and will be causing droug...,"{'longitude': -114.818269, 'latitude': 31.3322...","{'fullName': 'Arizona, USA', 'name': 'Arizona'...","{'username': 'SunDevil31673', 'displayname': '..."

In [29]:
df.isnull().sum()

id                0
date              0
content           0
coordinates    7067
place          7067
user              0
dtype: int64

In [27]:
#saving to csv
df.to_csv('../Data/tweets_without_geo.csv')

In [30]:
df

,id,date,content,coordinates,place,user
0,1394218085780017154,2021-05-17 09:07:49+00:00,John Kerry @ClimateEnvoy @JohnKerry #JohnKerry...,None,None,"{'username': 'Zermin', 'displayname': 'Helmut ..."
1,1394218077584117760,2021-05-17 09:07:47+00:00,humans killing each other and are the very r...,None,None,"{'username': 'hell_nikk', 'displayname': 'Nikh..."
2,1394218059188129794,2021-05-17 09:07:43+00:00,“Fact” check to fit truth to power — “There is...,None,None,"{'username': 'lucasbergkamp', 'displayname': '..."
3,1394218020189442048,2021-05-17 09:07:33+00:00,Energy And Climate Change Practice Lead\nhttps...,None,None,"{'username': 'TendersNgo', 'displayname': 'NGO..."
4,1394218019962884099,2021-05-17 09:07:33+00:00,Small actions such as planting a tree can make...,None,None,"{'username': 'CAN_Tanzania', 'displayname': 'C..."
...,...,...,...,...,...,...
7185,1393663377935904778,2021-05-15 20:23:36+00:00,Images of Elva the Eco Dragon 2.0 Mac version ...,None,None,"{'username': 'R_Tsakalidis', 'displayname': 'T..."
7186,1393663163388682242,2021-05-15 20:22:45+00:00,I'm one of the people who are committed to dis...,None,None,"{'username': 'Blasterella', 'displayname': 'Er..."
7187,1393662975039442948,2021-05-15 20:22:00+00:00,Opinion: It’s time to recommit to controlling ...,None,None,"{'username': 'ColoradoSun', 'displayname': 'Th..."
7188,1393662967024082945,2021-05-15 20:21:59+00:00,WARNINGS OF THE DESTRUCTION CLIMATE CHANGE IS ...,None,None,"{'username': 'Sonialowe1938', 'displayname': '..."
7189,1393662860031520768,2021-05-15 20:21:33+00:00,If climate change is and will be causing droug...,"{'longitude': -114.818269, 'latitude': 31.3322...","{'fullName': 'Arizona, USA', 'name': 'Arizona'...","{'username': 'SunDevil31673', 'displayname': '..."

In [ ]:
count = 0

for i in range(1, 100):
    count += 1
    if count < 3:
        print('Starting iterations')
        mx = df['id'].iloc[-1]
        df1 = pd.DataFrame(itertools.islice(sntwitter.TwitterSearchScraper(
            '(climate change) OR (global warming) OR (climate hoax) exclude:replies exclude:retweets lang:en max_id:%s' % mx).get_items(), 500))[['id', 'date', 'content', 'coordinates', 'place', 'user']]
        df1 = df1.iloc[1:]
        df = df.append(df1, ignore_index=True)
        print('Iteration #', i, 'done.')
        time.sleep(20)
    else:
        print('going to sleep')
        time.sleep(180)
        count = 0
        print('waking up')
        continue

,id,date,content,coordinates,place,user
0,1394218085780017154,2021-05-17 09:07:49+00:00,John Kerry @ClimateEnvoy @JohnKerry #JohnKerry...,None,None,"{'username': 'Zermin', 'displayname': 'Helmut ..."
1,1394218077584117760,2021-05-17 09:07:47+00:00,humans killing each other and are the very r...,None,None,"{'username': 'hell_nikk', 'displayname': 'Nikh..."
2,1394218059188129794,2021-05-17 09:07:43+00:00,“Fact” check to fit truth to power — “There is...,None,None,"{'username': 'lucasbergkamp', 'displayname': '..."
3,1394218020189442048,2021-05-17 09:07:33+00:00,Energy And Climate Change Practice Lead\nhttps...,None,None,"{'username': 'TendersNgo', 'displayname': 'NGO..."
4,1394218019962884099,2021-05-17 09:07:33+00:00,Small actions such as planting a tree can make...,None,None,"{'username': 'CAN_Tanzania', 'displayname': 'C..."
...,...,...,...,...,...,...
7185,1393663377935904778,2021-05-15 20:23:36+00:00,Images of Elva the Eco Dragon 2.0 Mac version ...,None,None,"{'username': 'R_Tsakalidis', 'displayname': 'T..."
7186,1393663163388682242,2021-05-15 20:22:45+00:00,I'm one of the people who are committed to dis...,None,None,"{'username': 'Blasterella', 'displayname': 'Er..."
7187,1393662975039442948,2021-05-15 20:22:00+00:00,Opinion: It’s time to recommit to controlling ...,None,None,"{'username': 'ColoradoSun', 'displayname': 'Th..."
7188,1393662967024082945,2021-05-15 20:21:59+00:00,WARNINGS OF THE DESTRUCTION CLIMATE CHANGE IS ...,None,None,"{'username': 'Sonialowe1938', 'displayname': '..."
7189,1393662860031520768,2021-05-15 20:21:33+00:00,If climate change is and will be causing droug...,"{'longitude': -114.818269, 'latitude': 31.3322...","{'fullName': 'Arizona, USA', 'name': 'Arizona'...","{'username': 'SunDevil31673', 'displayname': '..."